#!/usr/bin/python

from emv_applet import EMVShell

import gobject, gtk
import ccid

__copyright__ = 'Copyright (c) 2011 Gianni Tedesco'
__licence__ = 'GPLv3'

class CCIDApp(gtk.Container):
	pass

class CCIDeviceView(gtk.TreeView):
	def __init__(self, callback = None):
		self.callback = callback
		self.store = gtk.TreeStore(gobject.TYPE_PYOBJECT,
						gobject.TYPE_STRING,
						gobject.TYPE_STRING)
		gtk.TreeView.__init__(self, self.store)

		self.set_headers_visible(False)
		self.set_headers_clickable(False)
		self.set_enable_search(False)
		self.set_search_column(0)

		r = gtk.CellRendererText()
		i = gtk.CellRendererPixbuf()
		col = gtk.TreeViewColumn('Devices', None)
		col.pack_start(i, True)
		col.add_attribute(i, 'stock-id', 1)
		col.pack_start(r, True)
		col.add_attribute(r, 'text', 2)
		col.set_resizable(True)
		self.append_column(col)

		sel = self.get_selection()
		sel.connect('changed', self.__cb)
		self.refresh()

	def __cb(self, sel):
		if self.callback is None:
			return
		(store, i) = sel.get_selected()
		if i is None:
			return

		obj = store.get_value(i, 0)
		self.callback(obj)

	def __dev(self, itr, dev):
		i = 0
		for cci in dev.interfaces:
			try:
				cci.on(ccid.CHIPCARD_AUTO_VOLTAGE)
			except IOError:
				# maybe no card
				pass
			n = isinstance(cci, ccid.rfid) and 'Field' or 'Slot'
			t = isinstance(cci, ccid.rfid) and 'Tag' or 'Card'
			if cci.status in [ccid.CHIPCARD_PRESENT,
						ccid.CHIPCARD_ACTIVE]:
				status = '%s Present'%t
			else:
				status = 'Empty'
			label = '%s %d\n%s'%(n, cci.index, status)
			icon = gtk.STOCK_FILE
			self.store.append(itr, (cci, icon, label))
			i += 1

	def refresh(self):
		self.store.clear()

		for dev in ccid.devlist():
			try:
				d = ccid.ccid(dev, None)
			except:
				raise
			icon = gtk.STOCK_HARDDISK
			label = '%s\nBus %d, Address %d'%(d.name, d.bus, d.addr)
			itr = self.store.append(None, (d, icon, label))

			self.__dev(itr, d)

		self.expand_all()

		sel = self.get_selection()
		sel.select_path('0')

class CCIDApplets(gtk.Notebook):
	def __switch(self, _, __, idx):
		app = self.get_nth_page(idx)
		if self.callback is not None:
			self.callback(app)

	def __init__(self, cb = None):
		self.__map = {}
		self.callback = cb
		gtk.Notebook.__init__(self)
		self.connect('switch-page', self.__switch)

	def open_tab(self, parent, cci, app, title):
		if not self.__map.has_key(cci):
			x = app(parent, cci)
			x.show_all()
			idx = self.append_page(x, gtk.Label(title))
			self.set_tab_reorderable(x, True)
			self.__map[cci] = idx
		self.set_current_page(self.__map[cci])

class CCIDToolbar(gtk.Toolbar):
	def clear(self):
		n = self.get_n_items()
		for i in xrange(n):
			self.remove(self.get_nth_item(0))

	def set_toolbar(self, app):
		self.clear()
		items = app.toolbar()
		for (txt, iname, cb) in items:
			icon = gtk.Image()
			icon.set_from_stock(iname, gtk.ICON_SIZE_LARGE_TOOLBAR)
			item = gtk.ToolButton(icon, txt)
			item.set_tooltip_text(txt)
			item.set_is_important(True)
			item.set_visible_horizontal(True)
			item.set_visible_vertical(True)
			item.connect("clicked", cb)
			self.insert(item, -1)

		if self.get_n_items():
			self.show_all()
		else:
			self.hide_all()


class CCIDShell(gtk.Window):
	def toolbar(self, items):
		print items

	def status(self, status):
		self.__sb.pop(9)
		self.__sb.push(0, status)

	def destroy(self, *_):
		gtk.Window.destroy(self)
		gtk.main_quit()

	def select_item(self, item):
		if isinstance(item, ccid.ccid):
			print 'Selected device: %s'%item.name
			self.__tb.clear()
			return
		elif isinstance(item, ccid.slot):
			label = '%s slot: %d'%(item.owner.name, item.index)
		elif isinstance(item, ccid.rfid):
			label = '%s field: %d'%(item.owner.name, item.index)

		(desc, app) = self.apps['emv']
		self.__nb.open_tab(self, item, app, desc)

	def __app_select(self, app):
		self.__tb.set_toolbar(app)

	def __init__(self, apps = []):
		gtk.Window.__init__(self, gtk.WINDOW_TOPLEVEL)
		self.set_default_size(640, 480)
		self.set_title('CCID Utils')

		self.connect('destroy', self.destroy)
		agr = gtk.AccelGroup()
		(k, m) = gtk.accelerator_parse('<Control>Q')
		agr.connect_group(k, m, gtk.ACCEL_VISIBLE, self.destroy)
		(k, m) = gtk.accelerator_parse('<Control>W')
		agr.connect_group(k, m, gtk.ACCEL_VISIBLE, self.destroy)
		self.add_accel_group(agr)

		self.apps = {}
		for (name,desc,app) in apps:
			self.apps[name] = (desc,app)

		self.__sb = gtk.Statusbar()
		self.__tb = CCIDToolbar()
		self.__nb = CCIDApplets(self.__app_select)
		self.__app = {}

		vb = gtk.VBox()

		hp = gtk.HPaned()
		hp.add1(CCIDeviceView(self.select_item))
		hp.add2(self.__nb)

		vb.pack_start(self.__tb, False, False)
		vb.pack_start(hp)
		vb.pack_start(self.__sb, False, False)

		self.add(vb)
		self.show_all()
		self.__tb.hide()
		self.status('Scanned devices')

		gtk.main()
	
if __name__ == '__main__':
	CCIDShell([('emv', 'EMV Payment Card', EMVShell)])
