/* Generated by autober: do not modify */
#ifndef _PSE_FCI_H
#define _PSE_FCI_H


#define PSE_APP_PSE_PNAME              (1<<0U)


/* Tags for Payment System Directory ADF */
#define TAG_PSE_APP_PSE_ADF_NAME       0x004f
#define TAG_PSE_APP_PSE_LABEL          0x0050
#define TAG_PSE_APP_PSE_PNAME          0x9f12
#define TAG_PSE_APP_PSE_PRIO           0x0087

/* Tags for File Control Information */
#define TAG_PSE_FCI_PSE_APP            0x0061

/* Tags for root level */
#define TAG_PSE_FCI                    0x0070

struct pse_fci {
	struct pse_app {
		unsigned int _pse_adf_name_count;
		uint8_t pse_adf_name[16];
		unsigned int _pse_label_count;
		uint8_t pse_label[16];
		unsigned int _pse_pname_count;
		uint8_t pse_pname[16];
		uint8_t pse_prio;
		unsigned int _present;
	}pse_app;
};

struct pse_fci *pse_fci_decode(const uint8_t *ptr, size_t len);
void pse_fci_free(struct pse_fci *pse_fci);
#endif /* _PSE_FCI_H */
